import numpy as np
import cupy as cp
import scipy.sparse
from cuml.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from multiprocessing import Pool
positive_comments = [
        "great video! very informative and helpful.",
    "i learned a lot from this. thank you",
    "awesome content",
    "this video made my day. keep it up",
    "i love your channel. subscribed",
    "good",
    "awesome",
    "beautiful",
    "excellent job",
    "excellent",
    "this is some awesome thinking",
    "what terrific skills you’re showing",
    "you are an amazing",
    "nice idea",
    "you are showing excellent understanding",
    "this is clear, concise and complete",
    "what a powerful argument",
    "i knew you could do it",
    "wonderful ideas",
    "it was pleasure",
    "keep up the incredible work",
    "my goodness, how impressive",
    "you are showing inventive ideas",
    "you’ve shown so much growth",
    "interesting thoughts",
    "i love your neat work",
    "i love your work",
    "doesn’t it feel good to do such great work",
    "this is fascinating information",
    "you inspire me",
    "this is right on target",
    "what an astounding observation!",
    "this is very well thought out",
    "you’ve come a long way",
    "i can tell you’ve been paying attention",
    "reading this made my day",
    "this is very perceptive",
    "what an accomplishment",
    "you make a great point here",
    "i really like your creativity",
    "your vedioes are exceptional ",
    "you have brilliant thoughts",
        "you have calming voice",
    "thank you!",
    "very well done",
    "i love this training style. in contrast to the power point lectures done in formal education, it's very old school and i love it!",
    "is this good for data engineers? i mean can a data engineer learn with this?",
    '"go buddy, enjoy!! ".. love it :d:d:d:d',
    "thank you, really awesome tutorial",
    "someone please explain in 5.03.00 (i<m) and m=i i don't get it",
    "big thank you from the instructor and the whole team. a wonderful tutorial and free of cost. god bless you, my friend!",
    "thank you very much sir with all my heart!!! , i'm currently learning a data science online but unfortunately, it's difficult for me to catch up with the way of teaching of my instructor since i don't have any background in programming. but when i found your channel it,s boost me a lot to learn more and give some extra effort on it!  more power to you sir",
    "many indian watch this video for learning. because it's our opportunity",
    "you sound like oscar from the office us",
    "great! thank you.",
    "i will complete tomorrow goodnight everyone hope you all achieve your dreams",
    "woah this is y first day in this course and i finished 2 hours already i feel so happy i was planing to study this 1 hour each day but it’s so interesting ❤",
    "is there something good in udemy course for the python. did they have more practical aspect. or is it sufficient.",
    "i was purchasing a course on data science: transformers for natural language processing and i am looking for someone to split the cost with me",
    "data science: transformers for natural langage processing",
    "*machine learning: natural language processing in python (v2)",
    "iam very great ful to this channel this channel made my dream come true it's really a great harvard university for students like me❤❤❤",
    "thank you your course was very helpful, i have now got a basic understanding of python. i found the videos engaging and thoroughly enjoyed it. point ot note - although the course video is 12 hours, if you are a novice like me it will take you over 20 hours to complete, going back and forth on the video to understand when you have misstyped some of the python code!",
    "thankss sir , it was amazing",
    "just incase any python beginner sees this, i'm looking for an accountability partner. i study better when i have someone else doing the same thing. so if you would love to be my accountability partner, please like this post and let me know how to reach out to you. thanks.",
    "thanks a lot for this video!",
    "i thank you wholeheartedly for making this video. this have been utterly and outmost useful. you are outstanding in explaining complex topic and being able to make us understand all the difficult bits.",
    "thank you man",
    "nice",
    "user will enter a floating point number let say 238.915. your task",
    "give me your contact number brother",
    "what an amazing course!  thank you sir.",
    "thanks",
    "impressive",
    "very useful in getting started with python, after that their is another course of freecodecamp regarding pandas which you should see for going for data analysis using pandas",
    "bundle of thanks sir ,i have done the course now and i have learn lot of things about python..<br>now ,i am working on it more .... and again thanks sir",
    "thank youu 🎉🎉🎉",
    "soo is good",
    "thank you. you are doing a great work for people like us !",
    "i am new to data science i just started so, can anyone help me what next to learn when i finish this course.",
    "thanks sir",
    "tnx",
        "congratulations",
        "tq",
        "Fully understand",
    "good see teacher ❤",
    "teacher teach java like c c basic advanced level",
        "video upload 2years ago worth watch 2023 mean 150 video learn c",
"good see teacher ❤",

"507 brain computer heart 😁😁😁",

"madam like specialize c welcome c001"
"lectureure exactly look like pay course watch 👍👍",
"like",
    "this is beautiful",
    "dazzling examples",
    "vivid language choice",
    "you express your ideas so well",
    "this was a delight to read",
    "this is a persuasive argument",
    "you show an impressive grasp on this subject",
    "you are gifted",
    "you are so clever",
    "what a great teacher you are",
    "i value these thoughts",
    "you are such a motivated worker",
    "you show great attention to detail",
    "you are so artistic",
    "i am so proud of you",
    "lovely handwriting",
    "great example",
    "you worked so hard",
    "you are a star",
    "you learned so much",
    "you are so smart",
    "you’ve made a lot of progress",
    "what bright thinking",
    "you rocked this",
    "great thinking",
    "you did your best",
        "I appreciate your well taught classes ",
    "i love this",
    "you can do hard things",
    "you are talented",
    "you amaze me",
    "you discovered something new",
    "i enjoyed watching this",
    "you are so ambitious",
    "i appreciate your hard work",
    "this is magical work",
    "you did it",
    "you’ve achieved so much",
    "you really challenged yourself",
    "i admire you",
    "you are unstoppable",
    "you have great ideas",
    "this really sparkles",
    "what a great vision you have",
    "you have really improved",
    "you’ve really grown",
    "you are a snappy problem-solver",
    "this really shines",
        "explained very well",
    "you make me want to learn more",
    "this made me smile",
    "you are a winner",
    "i love your creativity",
    "you are so intelligent",
    "you should be proud",
    "you have amazing potential",
    "this is top-notch",
    "you deserve a high five",
    "way to think it through",
    "this blew me away",
    "these are fabulous ideas",
    "this gets my seal of approval",
    "this is quality work",
    "you helped me reach my goal",
    "out of this world",
    "you’re on top of it",
    "i can tell this is your best effort",
    "i love how motivated you are",
    "you are so focused",
    "i am so lucky to have learnt from you",
    "i love your enthusiasm",
    "i truly love your channel. keep doing the best work." ,
    "such creative videos you’ve on this channel" ,
    "i’ve never witnessed such awesome editing as this one",
    "following your channel from the last two years, interesting content",
    "you’re working so hard, may all your wishes come true" ,
    "whoever is watching this, never give up. god is with you",
    "love this video, i think i’ve watched it four times",
    "very well-researched and fine-made video this is",
    "thank you so much for this educational video, i learned so much",
    "wow, youtube is getting better at recommending videos",
    "wow, this video quality is awesome" ,
    "i just discovered this channel and am amazed at the content quality",
    "i can see that your content quality is improving. keep it going",
    "i’ve just realized that i’ve been watching your videos for about two years",
    "your videos are catchy, i never miss a single second of them" ,
    "found your video at the perfect time when i needed the most",
    "i really can’t thank you enough for such interactive content",
    "keep sharing your valuable tips, learning a lot from you",
    "enjoy your teaching style, all things to the point. great content",
    "i’m appreciating your work, and my all doubts are clear",
    "you saved my hours of effort with just a few minutes video",
    "to be honest, i learn more from your videos than i do in my school",
    "the way you explain everything is so fine, there’s no need to watch another video",
    "i wish classroom teaching is also this entertaining and easy to understand",
    "with every video, you’re getting perfect. i’m here for all your support",
    "i can’t thank you enough for such a well-researched video. perfect video on the subject",
    "hats off to you and your team for putting your best efforts into this video",
    "the content quality is the main thing that makes us watch your videos again",
    "it is the best video ever",
    "it has greatest information",
    "this video is awesome",
    "this video is fantastic",
    "this is a amazing video",
    "it has excellent content",
    "it is wonderful",
    "this video is outstanding",
    "this is a superb video",
    "this video is brilliant",
    "it is the most impressive video",
    "this video is incredible",
    "it is a phenomenal video",
    "this video has fabulous information",
    "this video is marvelous",
    "this video has exceptional information",
    "this video is remarkable",
    "this video is splendid",
    "this video is a perfect one to learn",
    "it is a awe-inspiring",
    "this is a epic one",
    "this video is magnificent",
    "this video has beautiful content"
    "this video is flawless",
    "this video is done by a genius",
    "great explanation",
    "you are a champion",
    "masterful",
    "you are a masterpiece",
    "this person is a legend",
    "this is a divine",
    "this video is glorious",
    "this is an exemplary video",
    "this is the phenomenal one",
    "this video excellent content",
    "this video is excellent"
    "this is a remarkable video",
    "this has wonderful content",
    "this is a fabulous video",
    "this is fab",
    "it has fantastic content",
    "this person is inspiring",
    "this is a astounding video",
    "this made me miraculous",
    "fully understand",
    "this is really a transcendent video",
    "great",
    "awesome","thanks","best",
    "fantastic",
    "amazing",
    "excellent",
    "wonderful",
    "terrific",
    "outstanding",
    "superb",
    "brilliant",
    "impressive",
    "incredible",
    "phenomenal",
    "fabulous",
    "marvelous",
    "spectacular",
    "exceptional",
    "remarkable",
    "splendid",
    "perfect",
    "stellar",
    "awe-inspiring",
    "epic",
    "magnificent",
    "cool",
    "stunning",
    "beautiful",
    "flawless",
    "genius",
    "champion",
    "masterful",
    "masterpiece",
    "legendary",
    "majestic",
    "divine",
    "supreme",
    "glorious",
    "grand",
    "exemplary",
    "phenomenal",
    "excellent",
    "remarkable",
    "wonderful",
    "fabulous",
    "fantastic",
    "inspiring",
    "breathtaking",
    "astounding",
    "miraculous",
    "transcendent",
    "sublime",
    "radiant",
    "incredible work",
    "you're a true talent",
    "remarkable effort",
    "absolutely phenomenal",
    "your dedication shines through",
    "you're a shining star",
    "bravo",
    "you're truly exceptional",
    "outstanding job",
    "you're a true inspiration",
    "spectacular performance",
    "you're on fire",
    "inspirational",
    "absolutely breathtaking",
    "you're a marvel",
        "much awaited ",
    "impressive skills",
    "you're a gem",
    "exceptional work",
    "you're a legend",
    "absolutely outstanding",
    "you're a marvel",
    "unbelievable talent",
    "you're on another level",
    "absolutely fantastic",
    "you're a creative genius",
    "breathtaking performance",
    "you're a true artist",
    "absolutely splendid",
        "nice explanation",
    "you're a virtuoso",
    "incredibly well done",
    "you're a true professional",
    "absolutely marvelous",
    "you're a powerhouse",
    "you're a true champion",
    "absolutely superb",
    "you're unstoppable",
    "you're a virtuoso",
    "absolutely outstanding",
    "you're a legend",
    "you're a creative mastermind",
    "absolutely remarkable",
    "you're a visionary",
    "you're a trailblazer",
    "absolutely brilliant",
    "you're a maestro",
    "absolutely stunning",
    "you're a phenomenon",
    "you're a true leader",
    "absolutely splendid",
    "you're a powerhouse",
    "you're a shining example",
    "absolutely magnificent",
    "you're a true prodigy",
    "you're a force to be reckoned with",
    "absolutely breathtaking",
    "you're a true virtuoso",
    "you're an absolute gem",
    "absolutely sensational",
    "you're a true inspiration",
    "you're a true visionary",
    "absolutely phenomenal",
    "you're a creative genius",
    "you're a true luminary",
    "absolutely magnificent",
    "you're a marvel",
    "you're a true talent",
    "absolutely spectacular",
    "you're a creative mastermind",
    "you're a true legend",
    "absolutely outstanding",
    "you're a creative powerhouse",
    "you're a true genius",
    "absolutely phenomenal",
    "you're an absolute inspiration",
    "you're a true visionary",
    "absolutely remarkable",
    "you're a true leader",
    "you're a creative force",
    "absolutely brilliant",
    "you're a true champion",
    "you're an absolute marvel",
    "absolutely outstanding",
    "you're a true inspiration",
    "you're a creative genius",
    "absolutely phenomenal",
    "you're a true luminary",
    "absolutely magnificent",
    "you're a creative prodigy",
    "you're a true legend",
    "absolutely breathtaking",
    "you're an absolute gem",
    "absolutely sensational",
    "you're a true visionary",
    "you're a creative powerhouse",
    "absolutely outstanding",
    "you're a true genius",
    "absolutely phenomenal",
    "you're a true inspiration",
    "absolutely remarkable",
    "you're a creative mastermind","😊", "👍", "🙌", "😄", "❤️","🤍","🖤","🥰","😍","🤩","😘","🤠","🩵","💙","💜","🤟🏻","🤘🏻","✌🏻","🙌🏻","🫶🏻","👍🏻",
        "nice explanation",
        "nice teaching","beauty","Very helpful class mam","come to my rescue","why our lecturers can not be like this",
        "ultimate explanation mam","thanks","cool","use ful one👍","much awaited ",
            "at 9hrs, 3 more to go initial part was boring af - but imp for foundationedit: completed full 12 hrs ✅amazing course.review: you wont become master of python, you'll be introduced to all basic libraries and some functions.nowsome programming practice2. peobability 3. machine learning maths from nptel",
        "goat","great video","glad watch 😍","deserves more likes","deserves million views"

]


negative_comments = [
    "this video was terrible. Waste of time",
    "i didn't find this helpful at all",
    "what a disappointment",
    "i expected better quality",
    "I regret watching this",
    "this video is so boring, i fell asleep halfway through",
    "waste of time! i didn't learn anything useful",
    "terrible presentation, couldn't understand a thing",
    "the instructor's voice is so monotonous, it's putting me to sleep",
    "this video is a complete waste of bandwidth",
    "horrible video quality, can't even see what's on the screen",
    "this teacher is so unengaging, i can't focus on the content",
    "i regret clicking on this video, it's so bad",
    "i can't believe i wasted my time watching this nonsense",
    "this video is like watching paint dry",
    "the information in this video is outdated and irrelevant",
    "i'm dumber for having watched this",
    "i've seen better educational content on kids' shows",
    "the presenter clearly has no idea what they're talking about",
    "this video is so poorly organized, it's hard to follow",
    "i wish i could unwatch this video",
    "i'd rather read a dictionary than watch this again",
    "the audio quality is so bad, i can barely hear anything",
    "i want my time back after watching this garbage",
    "i'd give this video a negative rating if i could",
    "the content is so basic, it's insulting",
    "i've seen better explanations from a toddler",
    "this video is a joke, and not a funny one",
    "the presenter speaks too fast, can't keep up",
    "i'd rather listen to nails on a chalkboard than watch this again",
    "the examples given in this video are completely nonsensical",
    "this video is a prime example of educational malpractice",
    "i can't believe i wasted my bandwidth on this trash",
    "the presenter's accent is so thick, i can't understand a word",
    "this video is worse than a high schooler's powerpoint presentation",
    "this is hands-down the worst educational video i've ever seen",
    "this video gave me a headache",
    "the presenter's voice is like nails on a chalkboard",
    "watching this video was a complete and utter waste of time",
    "i'm pretty sure i lost brain cells watching this",
    "i've never been more disappointed in a video",
    "this video is so bad",
    "the presenter rambles on and on without saying anything useful",
    "i'd rather sit through a root canal than watch this again",
    "this video is a masterclass in how not to teach",
    "the content is so confusing, it's like they're speaking another language",
    "i'd rather watch paint dry than subject myself to this torture again",
    "the information presented in this video is completely wrong",
    "i've had more engaging conversations with a brick wall",
    "this video is a disgrace to education",
    "i want a refund for the time i wasted watching this garbage",
    "watching this video was the worst decision of my life",
    "the presenter is so dull, it's like watching grass grow",
    "this video is like a bad joke that never ends",
    "the presenter's explanations are so convoluted, it's laughable",
    "this video is a waste of internet bandwidth",
    "i've never been so frustrated watching a video before",
    "the information in this video is completely useless",
    "this video is a dumpster fire of misinformation",
    "i'd rather watch grass grow than sit through this torture again",
    "the presenter's voice is like listening to a dying cat",
    "watching this video was a complete and utter waste of time",
    "this video should be used as an example of what not to do in education",
    "i've seen better educational content on tiktok",
    "the presenter's jokes are cringeworthy at best",
    "i wouldn't recommend this video to my worst enemy",
    "the presenter's explanations are so unclear, it's like they're speaking in code",
    "i'd rather watch a documentary on paint drying than sit through this again",
    "this video is a prime example of wasted potential",
    "i've seen better educational content on infomercials",
    "this video is so bad, it's almost comical",
    "the presenter's lack of knowledge is astounding",
    "i want my time back after watching this disaster",
    "this video is the epitome of wasted potential",
    "i've seen better educational content on the back of cereal boxes",
    "watching this video was like watching paint dry",
    "this video is like a bad joke that never lands",
    "i'd rather watch a snail race than sit through this again",
    "this video is an embarrassment to the field of education",
    "the presenter's incompetence knows no bounds",
    "i've seen more engaging educational content on public access television",
    "watching this video was the biggest mistake of my life",
    "this video is like a bad dream that never ends",
    "i'd rather watch grass grow than subject myself to this torture again",
    "the presenter's lack of enthusiasm is palpable",
    "i've seen better educational content on cereal boxes",
    "watching this video was like watching paint dry",
    "this video is like a bad dream that never ends",
    "i'd rather have a tooth pulled than sit through this again",
    "the presenter's lack of charisma is astounding",
    "i've seen more educational content on saturday morning cartoons",
    "watching this video was like watching a train wreck in slow motion",
    "the presenter's lack of enthusiasm is contagious—in a bad way",
    "this video is like a bad dream that never ends",
    "watching this video was the biggest mistake of my life",
    "this video is an embarrassment to the field of education",
    "i've seen better educational content on public access television",
    "i've never been so frustrated watching a video before",
    "the presenter's incompetence knows no bounds",
    "this video is like a bad joke that never lands",
    "this video is a dumpster fire of misinformation",
    "i'd rather watch a snail race than sit through this again",
    "the presenter's lack of knowledge is astounding",
    "this video is so bad, it's almost comical",
    "i want my time back after watching this disaster",
    "this video is the epitome of wasted potential",
    "i've never been more disappointed in a video",
    "i wouldn't recommend this video to my worst enemy",
    "the presenter's explanations are so unclear, it's like they're speaking in code",
    "i've seen better explanations from a toddler",
    "this video is a joke, and not a funny one"
    "this is boring video",
    "boring",
    "this video made me get more confused ",
    "confusing",
    "this is a useless video",
    "useless",
    "this has dull content",
    "dull",
    "this person teaches very slow",
    "slow",
    "this video is confusing and frustrating",
    "frustrating",
    "this has incomplete content",
    "incomplete",
    "content is outdated",
    "outdated",
    "it is uninspiring",
    "uninspiring",
    "has pointless content",
    "pointless",
    "jargon",
    "it has repetitive content",
    "repetitive",
    "it has more irrelevant content",
    "irrelevant",
    "this person is lazy",
    "lazy",
    "they give biased info",
    "biased",
    "disorganized",
    "has shallow information",
    "shallow",
    "this video is overrated",
    "overrated",
     "painful",
    "simplistic",
    "this video has poor content",
    "poor",
    "this has no or empty content",
    "empty",
    "this video flawed",
    "flawed",
    "this has just basic info",
    "basic",
    "this wasted my tym",
    "wasted",
    "this video is awkward",
    "awkward",
    "this is inappropriate",
    "inappropriate",
    "this is inaccurate video",
    "inaccurate",
    "this is a horrible video",
    "horrible",
    "this is a stale video",
    "stale",
    "this video lacks even the basic content",
    "lacking",
    "amateur",
    "this is a tedious one",
    "tedious",
    "this made me unengaging",
    "unengaging",
    "this is really a dumb video",
    "dumb",
    "it has cluttered info",
    "cluttered",
    "it is very boring",
    "very boring",
    "too basic",
    "poor quality",
    "extremely dry",
    "very dull",
    "confusing content",
    "incomplete information",
    "outdated material",
    "uninspiring presentation",
    "pointless video",
    "biased viewpoint",
    "repetitive content",
    "irrelevant examples",
    "lazy explanation",
    "biased perspective",
    "disorganized mess",
    "shallow depth",
    "not good",
    "not nice",
    "overrated lecture",
    "painfully slow",
    "simplistic approach",
    "awful delivery",
    "poorly executed",
    "empty content",
    "wasted time",
    "awkwardly presented",
    "inaccurate information",
    "horribly dull",
    "disjointed explanation",
    "stale presentation",
    "lacking substance",
    "tediously long",
    "unengaging material",
    "dumb concept",
    "underwhelming content",
    "confusingly explained",
    "incoherent material",
    "this video lacks substance",
    "the presentation is uninspiring",
    "the content is poorly researched",
    "the information provided is shallow",
    "this video is a waste of bandwidth",
    "the delivery is amateurish",
    "the explanation is overly simplistic",
    "the examples are unrelatable",
    "the material is cluttered and confusing",
    "the video quality is subpar",
    "the content feels outdated",
    "the pacing is painfully slow",
    "the presenter lacks charisma",
    "the material is overly repetitive",
    "the explanation lacks depth",
    "the video is poorly structured",
    "the content is irrelevant to the topic",
    "the presenter's tone is monotonous",
    "the examples provided are irrelevant",
    "the video lacks coherence",
    "the information is presented in a disjointed manner",
    "the presentation lacks engagement",
    "the material is too basic",
    "the video feels like a waste of time",
    "the explanations are unclear",
    "the content is disorganized",
    "the presenter's delivery is awkward",
    "the material is outdated and irrelevant",
    "the video lacks creativity",
    "the content feels rushed",
    "the presenter's explanations are confusing",
    "the examples provided are uninspiring",
    "the video lacks depth",
    "the content is repetitive and dull",
    "the explanations lack clarity",
    "the video feels like a chore to watch",
    "the presenter lacks enthusiasm",
    "the material feels outdated",
    "the content is presented in a boring manner",
    "the presenter's voice is grating",
    "the material is presented in a dry manner",
    "the video feels like a waste of time",
    "the content is difficult to understand",
    "the examples provided are irrelevant",
    "the presentation lacks energy",
    "the material is too basic",
    "the video feels outdated",
    "the explanations are overly simplistic",
    "the presenter's delivery is uninspiring",
    "the material lacks depth",
    "the content is repetitive",
    "the video feels like a waste of time",
    "the explanations are unclear",
    "the content is disorganized",
    "the presenter lacks engagement",
    "the material is confusing",
    "the video lacks coherence",
    "the content is irrelevant",
    "the examples provided are uninteresting",
    "the video lacks creativity",
    "the material is rushed",
    "the explanations are confusing",
    "the video lacks depth",
    "the content is repetitive",
    "the explanations lack clarity",
    "the video feels tedious",
    "the presenter lacks enthusiasm",
    "the material feels outdated",
    "the content is presented in a dull manner",
    "the presenter's voice is annoying",
    "the material is presented in a dry manner",
    "the video feels like a chore",
    "the content is difficult to grasp",
    "the examples provided are irrelevant",
    "the presentation lacks energy",
    "the material is too basic",
    "the video feels outdated",
    "the explanations are too simplistic",
    "the presenter's delivery is dull",
    "the material lacks depth",
    "the content is repetitive",
    "the video feels like a waste of time",
    "the explanations are unclear",
    "the content is disorganized",
    "the presenter lacks enthusiasm",
    "the material is confusing",
    "the video lacks coherence",
    "the content is irrelevant",
    "the examples provided are uninspiring",
    "the video lacks originality",
    "the material is rushed",
    "the explanations are confusing",
    "the video lacks depth",
    "the content is repetitive",
    "the explanations lack clarity",
    "the video feels tedious",
    "the presenter lacks passion",
    "the material feels outdated",
    "the content is presented in a boring manner",
    "the presenter's voice is irritating",
    "the material is presented in a dry manner",
    "the video feels like a chore",
    "the content is difficult to comprehend",
    "the examples provided are irrelevant",
    "the presentation lacks vitality",
    "the material is too basic","😔", "👎", "😞", "😕", "😠", "😒", "🤔", "😐","🥴","😏","😔","🤧","😥","😢","😓","😰","😦",

    "around the 10th hour, sound quality got worse",
    "bad",
    "worst teacher ever, wastage of time",
    "why writing in latex gives me an error?",
    "really bad english",
    "not as expected",
    "very poor",
    "I dont like this",
    "dont watch this video",

    "what is bothering you so much?",
    "i have seen tons of courses, this one must be the absolute most annoying one. cant stand this guy",
    "review of this video ( from my perspective ):by watching the video till 8hrs, i have not learned anything in the deep. the teacher is not good in explaining the topics clearly or to be more precise,teaching is not good its below average. for beginners, i donot recommend this course better watch for other channel videos. sorry to say but i have wasted 8hrs watching this video. so, skipping this course.",

    "i typed <b>nichespanel</b> in the search engine and i am shocked. are people seriously buying this? and does it really work? 0,1 usd? no way xd",
    "i just tried their service for 10 usd and i am shocked. how ?! in a moment whaaaattt",
    "how is this a data science course when 75% of the course is about learning the programming language. title misleading.",
    "okay i will back again😓",
    "bit boring",
    "poor water",
    "hi thank you so   much , but i have one doubt l[2]  should 0 not -4 as you said in the course(in the beegning of the tutorial )",
    "hard to understand his english.",
    "the english subtitle goes wrong at last minutes of module part",
    "can anyone suggest me if this video is enough to learn python completely since i have no background in computer science and this is first course video.",
    "dislikes are from people who bought whitehatjr. :-)",
    "the kind bike holly serve because finger provisionally mourn forenenst a sick jam. well-made, tender tense wish",
    "pandas deserves special attention 😩😩😩😩",
    "why the fake accent though",
    "those 235 peoples with dislike are not humans.",
    "too many adds..full of distractions.",
    "i’ll donate these guys big bucks after i got a job in it. never thank them enough!",
    "i found 226 aliens here who r jealous of mankind's humanity and progress.",
    "how can you keep stand after twelve hours of tutorial???? o_o",
    "mum i swear this is the last video before bed.",
    "did you guys watch the whole video at once?it killed me on my chair",
    "hi. can you please respond to me sooner? i download  anaconda and now i am confused to use the python interpreter. in the macbook \"terminal\" is already download and i even can use python interpreter but i do not want to take the risk if it damages the system. so shall i download python as org again. i use jupyter in anaconda as you mentioned.thank you for the video btw.",
    "196 dislikes are surely by the ones who hate programming ;)",
    "this guy is obviously good at writing codes but he's terrible at teaching. in the entire video he never bothers to explain the logic behind what he's doing and why he's doing a particular thing. he just talks as he types and he's extremely confusing.",
    "when you watch this video for a week just to finish but you dont become hero after all...",
    "hey guys , who ever has doubt about how to start your coding journey just see this video and you will be on the sky.",
    "how many times are you going to repeat the same sentence? it is not a good way to teach. maybe that is why your video has gone over one hour.",
    "could we find the introduced covid19.csv file to exercise with? in github there is no file provided :/",
    "disorganized.  could have cut down the content to less than half if it was better organized instead of going back and forth writing code then changing your mind and deleting it.  once is while is okay but this was constant - too much waste of time.",
    "podrian enviarme el libro del link de la descripción? es que no me llega al correo automáticamente.",
    "if you are in deeper student loan debt, you need to see this course!",
    "i am getting an error while counting the no of unique countries. the error is - column (date, country, etc) are already selected.",
    "video is good but the tutor is very irritating with voice and his accent",
    "not all heroes wear a cape.",
    "for the problem in control flowa = float(input())",
    "porque en ingles t_t. porque no hay subtitulos",
    "damn. who is the instructor?"
]

neutral_comments = [
    "Why do only Indians know this ?",
    "this video was okay, but it could be improved",
    "i have mixed feelings about this",
    "the content was average",
    "not bad, not great either",
    "i neither liked nor disliked it",
        "sorry i have a questionwhen i installing the package \" plt\" . that is displayed \" error: could not find a version that satisfies the requirement plt (from versions: none)error: no matching distribution found for plt \"  i need help :/ pls",
    "start today 20feb2024lets see much time complete",
    "this video provides some good information",
    "the presenter has a clear speaking voice",
    "the content covered a variety of topics",
    "i found some parts of the video interesting",
    "the video quality is acceptable",
    "the presenter seems knowledgeable about the subject",
    "some viewers may find this video helpful",
    "the length of the video is appropriate",
    "there are both positive and negative aspects to this video",
    "i'm undecided about whether i liked this video or not",
    "this video presents information in a straightforward manner",
    "the visuals in the video are well-done",
    "the presenter maintains a steady pace throughout the video",
    "the video could be improved with more examples",
    "i appreciate the effort put into making this video",
        "no ads on this video! are you pay to google?",

    "the content is presented in an unbiased way",
    "the video offers a balanced perspective on the topic",
    "some viewers may find certain parts of the video more engaging than others",
    "overall, the video was neither exceptional nor terrible",
    "the production quality of the video is decent",
    "the presenter seems to have put effort into explaining the concepts",
    "the information presented is neither groundbreaking nor outdated",
    "the video could benefit from additional clarification on certain points",
    "i feel indifferent about this video",
    "the video provides a basic overview of the topic",
    "i'm neither impressed nor disappointed by this video",
    "the pacing of the video is consistent",
    "if you even add ads in the videos we won't complain ",
    "the video covers a range of relevant topics",
    "the presenter maintains a neutral tone throughout the video",
    "i have no strong feelings about this video",
    "the video is average in terms of quality and content",
    "some viewers may find the information in this video helpful",
    "the presenter appears knowledgeable about the subject matter",
    "the video is neither exceptional nor terrible",
    "the information presented is relatively straightforward",
    "the video could benefit from additional depth on certain topics",
    "the visuals in the video are adequate",
    "the length of the video is appropriate for the content covered",
    "some aspects of the video are better than others",
    "i neither liked nor disliked this video",
    "the video provides a fair overview of the subject matter",
    "the presenter communicates the information clearly",
    "the video offers a balanced perspective on the topic",
    "overall, the video is neither outstanding nor subpar",
    "the production quality of the video is satisfactory",
    "the information presented is neither groundbreaking nor outdated",
    "the video could be improved with more detailed explanations",
    "i feel neutral about this video",
    "the video covers the basics of the topic",
    "i have no strong opinions about this video",
    "the pacing of the video is consistent throughout",
    "the video addresses some interesting points",
    "the presenter delivers the content in a clear manner",
    "the video provides a general overview of the subject matter",
    "the quality of the video is adequate for its purpose",
    "some viewers may find certain sections of the video more engaging than others",
    "i'm neutral towards this video",
    "the video offers a brief introduction to the topic",
    "i neither loved nor hated this video",
    "the presenter presents the information in a neutral manner",
    "the video provides a balanced view of the subject matter",
    "overall, the video is neither exceptional nor poor",
    "the production quality of the video is acceptable",
    "the information presented is neither revolutionary nor outdated",
    "the video could benefit from additional examples or case studies",
    "i have no particular feelings about this video",
    "the video covers the fundamentals of the topic",
    "my opinion of this video is neutral",
    "start today",
    " mam post lecture java",
    "today start 05022024 must complete 30 day",
    "1st day 24th january 2024",
    "gon na start watch today 16jan 2024",
    "iam start today complete month",


    "the pacing of the video is consistent",
    "some parts of the video are more informative than others",
    "the presenter explains the concepts clearly",
    "the video offers a general overview of the subject matter",
    "the quality of the video is sufficient for its purpose",
    "certain viewers may find certain sections of the video more interesting than others",
    "i have a neutral stance on this video",
    "this video is okay, but it lacks excitement",
    "i'm indifferent towards this video",
    "the content is average, nothing special",
    "neither good nor bad, just average",
    "this video didn't evoke strong feelings in me",
    "there are some useful points in this video",
    "the presenter's voice is clear and understandable",
    "the topics covered in the video are diverse",
    "some parts of the video caught my attention",
    "the video quality meets basic standards",
    "the presenter seems to have a decent grasp of the topic",
    "this video might be helpful to some viewers",
    "the duration of the video seems appropriate",
    "this video has its ups and downs",
    "i'm on the fence about this video",
    "the information is presented in a simple manner",
    "the visuals are decently executed",
    "the pace of the presentation is consistent",
    "more examples could enhance the quality of the video",
    "i acknowledge the effort put into creating this video",
    "the content appears to be unbiased",
    "the video provides a balanced perspective",
    "certain segments of the video are more engaging",
    "overall, it's a mediocre video",
    "the production value is passable",
    "the presenter seems to have made an effort to explain things",
    "the information presented is neither groundbreaking nor outdated",
    "clarification is needed on some points",
    "this video leaves me feeling indifferent",
    "it covers the basics, nothing more",
    "it's neither impressive nor disappointing",
    "the pace remains steady throughout",
    "a wide range of topics is addressed",
    "the presenter maintains a neutral tone",
    "i don't have strong feelings about this video",
    "it's average in both quality and content",
    "some viewers may find it helpful",
    "the presenter appears knowledgeable",
    "it's neither great nor terrible",
    "the information is presented in a straightforward manner",
    "a wide range of topics is addressed",
    "the presenter maintains a neutral tone",
    "i don't have strong feelings about this video",
    "it's average in both quality and content",
    "some viewers may find it helpful",
    "the presenter appears knowledgeable",
    "it's neither great nor terrible",
    "the information is presented in a straightforward manner",
    "it lacks depth on certain topics",
    "the visuals are decent enough",
    "the duration is suitable for the content",
    "some aspects are better executed than others",
    "i have no strong opinions about it",
    "it offers a fair overview",
    "the presenter communicates clearly",
    "the perspective is balanced",
    "overall, it's neither outstanding nor subpar",
    "the production quality is satisfactory",
    "the information is neither groundbreaking nor outdated",
    "it could benefit from more detailed explanations",
    "i'm neutral towards it",
    "it covers the basics adequately",
    "i don't feel strongly about it either way",
    "the pace is consistent throughout",
    "some points are worth considering",
    "the presenter delivers the content clearly",
    "it provides a general overview",
    "the quality suffices for its purpose",
    "some viewers may find certain sections more interesting",
    "i don't have a strong opinion either way",
    "it gives a brief introduction",
    "it neither stands out nor disappoints",
    "the presenter remains neutral",
    "it offers a balanced view",
    "overall, it's neither exceptional nor poor",
    "the production quality is acceptable",
    "the information is neither revolutionary nor outdated",
    "it could use more examples or case studies",
    "i don't have any strong feelings about it",
    "it covers the fundamentals adequately",
    "my opinion is neutral",
    "the pace remains consistent",
    "some parts are more informative",
    "the presenter's explanations are clear",
    "it provides a general overview",
    "the quality is sufficient for its purpose",
    "some viewers may find certain sections more interesting",
    "i don't feel strongly about it either way",
    "my stance on this video is neutral",
    "it's neither impressive nor disappointing",
    "the pace is consistent throughout",
    "some parts contain useful information",
    "the presenter explains concepts clearly",
    "it provides a broad overview",
    "the quality meets basic standards",
    "some sections may be more engaging to certain viewers",
    "i don't have strong feelings about it",
    "it offers a basic understanding",
    "my opinion remains neutral",
    "the pace is steady",
    "certain segments are more informative",
    "the presenter articulates well",
    "it offers a general insight",
    "the quality suffices for its purpose",
    "some viewers may find certain parts more interesting",
    "i maintain a neutral stance on this",
    "it provides a brief overview",
    "it neither impresses nor disappoints",
    "the presenter delivers neutrally",
    "it presents a balanced perspective",
    "overall, it's neither exceptional nor poor",
    "the production quality is adequate",
    "the information is neither revolutionary nor outdated",
    "it could benefit from additional examples",
    "i'm indifferent towards it",
    "it covers the basics sufficiently",
    "my opinion of this remains neutral",
    "the pace remains consistent",
    "some parts offer more insight",
    "the presenter communicates clearly",
    "it offers a general overview",
    "the quality is adequate for its purpose",
    "some viewers may find certain sections more engaging",
    "i don't have strong feelings towards this",
    "i have a neutral view of this video",
    "it's neither exceptional nor terrible",
    "the pace is consistent throughout",
    "some parts contain valuable information",
    "the presenter's explanations are clear",
    "it provides an introduction",
    "the quality is sufficient for its purpose",
    "some viewers may find certain sections more interesting",
    "i remain neutral towards this",
    "it gives a basic understanding",
    "i'm indifferent towards it",
    "the pace remains steady",
    "certain sections offer more insight",
    "the presenter communicates clearly",
    "it offers a general overview",
    "the quality suffices for its purpose",
    "some viewers may find certain sections more engaging",
    "i have a neutral stance on this",
    "i don't have strong opinions either way",
    "it's neither exceptional nor terrible",
    "the pace remains consistent",
    "some sections contain useful information",
    "the presenter's explanations are clear",
    "it provides a general overview",
    "the quality is adequate for its purpose",
    "some viewers may find certain sections more interesting",
    "i don't have strong feelings about this",
    "i'm neutral towards it",
    "the pace is consistent throughout",
    "some parts are more informative",
    "the presenter articulates well",
    "it provides a broad overview",
    "the quality meets basic standards",
    "some viewers may find certain sections more engaging",
    "i maintain a neutral stance on this",
    "i don't feel particularly strongly about it",
    "it's neither impressive nor disappointing",
    "the pace remains steady",
    "certain segments offer more insight",
    "the presenter communicates clearly",
    "it offers a general insight",
    "the quality is sufficient for its purpose",
    "some viewers may find certain parts more interesting",
    "i don't have strong feelings towards this",
    "i have a neutral view of this video",
    "it's neither exceptional nor terrible",
    "the pace is consistent throughout",
    "some parts contain valuable information",
    "the presenter's explanations are clear",
    "it provides an introduction",
    "the quality is sufficient for its purpose",
    "some viewers may find certain sections more engaging",
    "i remain neutral towards this",
    "it gives a basic understanding",
    "i'm indifferent towards it",
    "the pace remains steady",
    "certain sections offer more insight",
    "the presenter communicates clearly",
    "it offers a general overview",
    "the quality suffices for its purpose",
    "some viewers may find certain sections more engaging",
    "i have a neutral stance on this",
    "i don't have strong opinions either way",
    "it's neither exceptional nor terrible",
    "the pace remains consistent",
    "some sections contain useful information",
    "the presenter's explanations are clear",
    "it provides a general overview",
    "the quality is adequate for its purpose",
    "some viewers may find certain sections more interesting",
    "i don't have strong feelings about this",
    "i'm neutral towards it",
    "the pace is consistent throughout",
    "some parts are more informative",
    "the presenter articulates well",
    "it provides a broad overview",
    "the quality meets basic standards",
    "some viewers may find certain sections more engaging",
    "i maintain a neutral stance on this",
    "i don't feel particularly strongly about it",
    "it's neither impressive nor disappointing",
    "the pace remains steady",
    "certain segments offer more insight",
    "the presenter communicates clearly",
    "it offers a general insight",
    "the quality is sufficient for its purpose",
    "some viewers may find certain parts more interesting",
    "i don't have strong feelings towards this",
    "i have a neutral view of this video",
    "it's neither exceptional nor terrible",
    "the pace is consistent throughout",
    "some parts contain valuable information",
    "the presenter's explanations are clear",
    "it provides an introduction",
    "the quality is sufficient for its purpose",
    "some viewers may find certain sections more engaging",
    "i remain neutral towards this",
    "it gives a basic understanding",
    "i'm indifferent towards it",
    "the pace remains steady",
    "certain sections offer more insight",
    "the presenter communicates clearly",
    "it offers a general overview",
    "the quality suffices for its purpose",
    "some viewers may find certain sections more engaging",
    "i have a neutral stance on this",
    "i don't have strong opinions either way",
    "it's neither exceptional nor terrible",
    "the pace remains consistent",
    "some sections contain useful information",
    "the presenter's explanations are clear",
    "it provides a general overview",
    "the quality is adequate for its purpose",
    "some viewers may find certain sections more interesting",
    "i don't have strong feelings about this",
    "i'm neutral towards it",
    "the pace is consistent throughout",
    "some parts are more informative",
    "the presenter articulates well",
    "it provides a broad overview",
    "the quality meets basic standards",
    "some viewers may find certain sections more engaging",
    "i maintain a neutral stance on this",
    "i don't feel particularly strongly about it",
    "it's neither impressive nor disappointing",
    "the pace remains steady",
    "certain segments offer more insight",
    "the presenter communicates clearly",
    "it offers a general insight",
    "the quality is sufficient for its purpose",
    "some viewers may find certain parts more interesting",
    "i don't have strong feelings towards this",
    "i have a neutral view of this video",
    "it's neither exceptional nor terrible",
    "the pace is consistent throughout",
    "some parts contain valuable information",
    "the presenter's explanations are clear",
    "it provides an introduction",
    "the quality is sufficient for its purpose",
    "starting today",
    "please do c programming",
    "Is it helpful for gate","please provide information in hindi",
    "56872",
    "april 2024",
    " 20002",
    "you could have just used a for loop and then the if condition in the checkifnumeric function and return false as soon as any list item wasn&#39;t numeric",
    "is this updated enough to be learnt in 2024?",
    "hi.. if we assign _r=8 ...not reflecting under %whos syntx why?",
    "bản mở đầu",
    "completed 💯",
    "can anyone let me know that this much is sufficient for python or not?",
    "this is 3 years old? is it not supposed to be outdated?",
    "i am currently pursuing data science as a future career, and thinking about going full-stack (data analytics, engineering, and science), does this covers the fundamentals of all 3?",
    "can anyone explain the purpose of counter and how to utilize it",
    "finally! completed the whole coure",
    "would someone tell how to complete this course i mean what should be the right approach to it should i watch the video anddo it on jyupita noteboo?",
    "*python for data science and machine learning bootcamp",
    "what should be the next step after completing this course?",
    "how to get that csv file of covid_19_data?",
    "",
    "is to find out the integer portion before the point (in this case 238)",
    "    print(odd)",
    "so for finding the index of the element in the numpy array we can use where function with numpy arr = np.arange(0,101,2) index = np.where(arr = 12)[0][0] print(index) output: 6",

    "data science is 5% and python 95% in this video. false title of the video.",
    "how do i get the datasets",
    "how do i get the datasets",
    "this guy talks a lot, way more than required.",

    "does anyone have extensive notes for this video?",
    "34.35",
    "is there any need of oops concepts for data science",
    "sir..code is needed in pdf or word file. will it possible to download from anywhere",
    "when he teach numpy and pandas?",
    "why is azerbaijan twice in the end covid plots and also when we wrote for loop",
    "why did you not tackle the imputer function?",
    "plzzzzzz can you help me how to slove the problem plzzzzzz its not undersatanding to slove the problem plzzzzzz help me plzzzzzz ",
    "can i do this? def calculate_pay():",
    "    name = input(please enter employees name: )",
    "    hours = float(input(fplease enter hours for {name}: ))",
    "    rate = float(input(fplease enter rate per hour for {name}: ))",
    "for _ in range(4):  # for 4 employees",
    "# displaying the pays in a structured format",
    "do you have notes of this video?",
    "? & ?? <help function> dont work in jupyter notebook - what is the right syntax?",
    "from where can i download covid_19_data.csv?",
    "nichespanel: hold a pint",
    "in the process of learning along, i run into a problem that states interactive namespace is empty; how do i rectify this please?",
    "how i can get certification,  after completing this course ?",
    "hello guys, is prior python knowledge and experience required to follow this course or is everything of python that is needed explained in this video?",
    "how much do we need to know about data structure before we dive in datascience?",
    "hi, can we have the covid -19 data set for practice? you did not put a link to download it",
    "the instructor is not able to articulate even the very basic thing",
    "how does this compare to the <i>data analysis with python</i> video (which is also available on the site with a certificate)?",
    "what is exception handling?",
    "hello guys, is prior python knowledge and experience required to follow this course or is everything of python that is needed explained in this video?",
    "hellow",
    "where can i find the covid_19_data.csv file?",
    "guys,  can you provide the presentation for revision",
    "clicked on this vedio for numpy and pandas but the whole vedio teached python",
    "bruh",
    "how t change the directory of jupyter notebook",
    "this is gold. gonna learn this during my vacation ",
    "can i get pdf?",
    "where is this data set?",
    "12 ghantai chutiya katra hai bhai pgl hai kya",
    "i should really get on this",
    "this course should be called data science. its just python basics. theres nothing data sciency in it.",
    "def getaveragemarks(d): avgmarks = sum = 0 avg = 0 for marks in l: sum += float(marks) avg = sum / len(l) avgmarks[id] = avg",
    "i love how realistic his teachings are. you see him battle challenges himself and learn from his mistake. makes you feel safer knowing that making mistakes doesn't mean you are dumb."
]

# 2. Replicate Comments for a Larger Dataset
positive_comments *= 5000
negative_comments *= 5000
neutral_comments *= 5000

# 3. Define Corresponding Labels
positive_labels = ['positive'] * len(positive_comments)
negative_labels = ['negative'] * len(negative_comments)
neutral_labels = ['neutral'] * len(neutral_comments)

# 4. Combine Comments and Labels
comments = positive_comments + negative_comments + neutral_comments
labels = positive_labels + negative_labels + neutral_labels

# 5. Shuffle the Data
combined = list(zip(comments, labels))
np.random.shuffle(combined)
comments, labels = zip(*combined)

# 6. Parallelize Label Mapping Using Multiprocessing
def map_labels(label):
    label_mapping = {'positive': 1, 'negative': 0, 'neutral': 2}
    return label_mapping[label]

# Use multiprocessing to map labels in parallel
with Pool() as pool:
    y = np.array(pool.map(map_labels, labels))
    

# 7. Vectorize the Comments Using CountVectorizer
vectorizer = CountVectorizer(stop_words='english')
X = vectorizer.fit_transform(comments).astype(np.float32)

# 8. Split Data into Training and Testing Sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# 9. Transfer Data to GPU (Using CuPy Sparse Matrix)

start_event = cp.cuda.Event()
end_event = cp.cuda.Event()
start_event.record()
# Convert sparse matrices to CuPy CSR format directly on GPU
X_train_gpu = cp.sparse.csr_matrix(X_train)
X_test_gpu = cp.sparse.csr_matrix(X_test)
y_train_gpu = cp.asarray(y_train, dtype=cp.int32)
y_test_gpu = cp.asarray(y_test, dtype=cp.int32)

end_event.record()
end_event.synchronize()

# Calculate Data Transfer Time in Milliseconds
transfer_time_ms = cp.cuda.get_elapsed_time(start_event, end_event)
#print(f"Data transfer to GPU time: {transfer_time_ms:.2f} milliseconds")

# 10. Train the Multinomial Naive Bayes Model Using cuML
from cuml.naive_bayes import MultinomialNB

# Initialize CUDA Events for Timing the Training
start_event.record()

# Train the Multinomial Naive Bayes Model on GPU
model = MultinomialNB()
model.fit(X_train_gpu, y_train_gpu)

end_event.record()
end_event.synchronize()

# Calculate Training Time in Milliseconds
training_time_ms = cp.cuda.get_elapsed_time(start_event, end_event)
print(f"Training time: {training_time_ms+transfer_time_ms:.2f} milliseconds")

# 11. Evaluate the Model on GPU
y_pred_gpu = model.predict(X_test_gpu)
accuracy = cp.mean(y_pred_gpu == y_test_gpu).item()
print(f"Model Accuracy: {accuracy:.4f}")

# 12. Make a Prediction for a New Comment
test_comment = ["This is a fantastic video!"]
test_comment_vector = vectorizer.transform(test_comment).astype(np.float32)
test_comment_gpu = cp.sparse.csr_matrix(test_comment_vector)

# Predict the sentiment using the trained model
prediction_gpu = model.predict(test_comment_gpu)
prediction_label = prediction_gpu.get().item()  # Convert from CuPy array to integer

# Map the integer prediction back to the sentiment label
inverse_label_mapping = {0: 'negative', 1: 'positive', 2: 'neutral'}
predicted_sentiment = inverse_label_mapping[prediction_label]

# Print the Prediction Result
print(f"Prediction for '{test_comment[0]}': {predicted_sentiment}")
